# layout -- 布局相关
# language: zh-CN

## menu 导航菜单显示
menu:
- page: Home
  url: /
  icon: fa-home
- page: categories
  url: /categories
  icon: fa-list
- page: archives
  url: /archives
  icon: fa-archive
- page: tags
  url: /tags
  icon: fa-tag
- page: about
  url: /about
  icon: fa-user


## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml


# 各个小工具的设置

## widgets
widgets:
- notification
- blog_info
- social
- category
- archive
- tagcloud
- friends

## 首页关于我设置
blog_info:
  image: /icons/wx.jpg
  author: Blant
  words: 菩提本无树，明镜亦非台，本来无一物，何处惹尘埃。

## 网站公告设置
notification: |-
            <p>
              <b>笔者微信</b>：Andrewblant，欢迎加我<br/>
            </p>

## 社交设置
social:
 - name: GitHub
   icon: github
   href: //github.com/andrewblant
 - name: Git@OSC
   icon: git
   href: //gitee.com/andrewblant
 - name: 邮箱
   icon: envelope-o
   href: mailto:blant@vip.qq.com
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 友链设置
links:
  - 导航: http://www.blant.com/navigation
  - 定制互联网+服务: http://www.inwe365.com/
  - 大平台: http://www.fly2you.cn/
##SpringCloud|周立: http://www.itmuch.com/


# 主题自定义个性化配置

## 网站宣传语
branding: 

## 懒加载图片占位符
placeholder: ./img/loading.gif

## 缩略图自定义随机图片
defaultImgs:
  - 

## 截取文章首页描述字数
excerptLength: 240

## 当无分类时显示文字，默认为'无'
noCategoryText: '无'

## 代码高亮配置
highlightTheme: railscasts

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## 文章过期提醒功能
warning:
  days: 30000
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 添加版权保护 
archiveCopyright:
  enable: true
  tip: '本博客由Blant创作，采用
    <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/" target="_blank">
    CC BY 3.0 CN
    </a>
    许可协议。可自由转载、引用，但需署名作者且注明文章出处。如转载至微信公众号，请在文末添加作者公众号二维码。'

## 过低版本的浏览器提醒文字
outdated_browser_text: '你使用的浏览器版本过低，为了你更好的阅读体验，请更新浏览器的版本或者使用其他现代浏览器，比如Chrome、Firefox、Safari等。'


## 主题评论
### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10


### 友言评论
uyan:
  enable: true
  uyan_id: 2148522


## 网站访问统计

## 网盟CNZZ网站统计
cnzz_anaylytics:
  enable: true  #是否启用
  hiden: false    #使用显示文字
  head: s13   #统计头
  id: 1268566472  #站长统计的ID
  
 # Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  enable: true
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>本站访客数
  site_uv_footer: 人次
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>本站总访问量
  site_pv_footer: 次
  
  page_pv: false
  page_pv_header: <i class="fa fa-file-o"></i>本文总阅读量
  page_pv_footer: 次


### 百度统计
#baidu_anaylytics: 13766878cde148282622871dd245a973

### 谷歌统计
#google_anaylytics: 

### 百度文章推送
#baidu_push:

codeing_host_by:
  enable: false

#网站主题配置
since: 2016
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.1.0
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
# 是否开启fork me on github
fork_me_on_github:
  enabled: true
  url: http://github.com/andrewblant
